### ISSUE TITLE
Not an issue, but rather a question about the project with a feature request…

### ISSUE THREAD

**Issue by ytrezq** [fergarrui/ethereum-graph-debugger#12]
Is there a public live instance somewhere ?
Does it require a full node for debugging Mainnet transactions ?

About transactions involving several contract address ?

**Comment by fergarrui** [comment]
Hi @ytrezq ,
There is no public instance. I was thinking about deploying it somewhere but it is not ready yet
It does require a full node for debugging past transactions, or you can use ganache fork feature to debug new transactions in mainnet.
If you are developing, you can just use ganache as blockchain and you can debug it (basically, every node that supports `debug_traceTransaction` is supported)

Transactions involving several contracts is supported, but you'll see only the trace of one contract at the time. If you want to check how the trace of an inner call looks like, you have to go to the inner contract involved in the transaction, and debug the transaction for that contract (I also want to improve this in the future, or at least make it more obvious to the user)

Thanks for your questions, please let me know if you need any clarification or help

**Comment by ytrezq** [comment]
You see, the problem for contracts calling contracts, is the transaction is the same for inner calls. And sometime the contract used inside inner calls requires `CALLER` to have `EXTCODESIZE`>0.

Remix is in a similar situation if the opcode used is a `DELEGATECALL`.

You see, many peoples in the world have an Internet connection speed slower to the one at which the blockchain grows.
That’s why I need an alternative to Remix, and it looks like you’re program can’t works because of the lack of proper subcontract call support.

Do you plan to add support for Metamask support for debugging Mainnet transactions without having a speed high enough to stay in sync with the blockchain ?

**Comment by fergarrui** [comment]
So, let's say we have: ContractA.sol, ContractB.sol and ContractC.sol

And there is a transaction that runs a function of ContractA.sol, that calls a function of ContractB.sol and then, ContractB.sol calls a function of ContractC.sol

So, when you open the application and select the path of your contract, you will see 3 tabs, one per contract.
In every tab you can do some actions, like debug a transaction.
If you are in the tab of ContractA.sol and you debug the transaction 0x12345, you will see the control flow graph of the contract + opcodes executed, including `CALL` and the next opcode will be the opcode after that `CALL` was executed (always ContractA.sol).
If you want to see what happened in ContractB.sol during that transaction, you'll need to go to the tab of ContractB.sol and debug the transaction 0x12345, there you will see everything that happened in ContractB.sol in 0x12345 transaction, but not what happened in ContractA.sol or ContractC.sol.
To see what happened in ContractC.sol, it is the same story, you go to that contract's tab, and debug 0x12345.

Metamask uses Infura underneath, and since Infura still does not support `debug_traceTransaction`, it is not possible to debug using it (no application is able to do that).

I created this ticket in Infura's Github: https://github.com/INFURA/infura/issues/123 , and hopefully it will be implemented in the future.
There is a settings dropdown in the top right where you can specify RPC endpoints different than http://127.0.0.1:8545 (default), and potentially you can point to infura when the above issue is implemented.

**Comment by fergarrui** [comment]
Closing the issue for inactivity
